// src/scripts/flexibleImport.ts
import * as fs from 'fs';
import * as path from 'path';
import * as XLSX from 'xlsx';
import { createClient } from '@supabase/supabase-js';
import { refreshSchema } from '../lib/supabaseSchema';
import { normalizeHeaders, detectIgnoredColumns } from '../lib/importHelpers/headerNormalizer';
import { generatePhone } from '../lib/importHelpers/phoneGenerator';
import { generateAcademicId } from '../lib/importHelpers/idGenerator';
import { generatePassword } from '../lib/importHelpers/passwordGenerator';
import { runWithRetry } from '../lib/supabase'; // existing retry wrapper

type RowOriginal = Record<string, any>;
interface RowResult {
  original: RowOriginal;
  processed: RowOriginal;
  warnings: string[];
  failed: boolean;
}

interface ImportReport {
  totalRows: number;
  successfulRows: number;
  failedRows: number;
  warningsCount: number;
  ignoredColumns: string[];
  autoFixedRows: number;
  rowDetails: RowResult[];
}

/**
 * Reads a workbook (Excel) or CSV file and returns a 2‑D array of raw rows.
 */
function readFile(filePath: string): any[][] {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === '.csv') {
    const data = fs.readFileSync(filePath, 'utf8');
    // simple split – CSV may contain commas inside quotes; using XLSX parsing for robustness
    const ws = XLSX.read(data, { type: 'string' });
    const sheet = ws.Sheets[ws.SheetNames[0]];
    return XLSX.utils.sheet_to_json(sheet, { header: 1, raw: true }) as any[][];
  }
  // default to Excel formats (.xlsx, .xls)
  const wb = XLSX.readFile(filePath, { cellNF: true, cellDates: true, sheetRows: 0, dense: true });
  const sheet = wb.Sheets[wb.SheetNames[0]];
  return XLSX.utils.sheet_to_json(sheet, { header: 1, raw: true }) as any[][];
}

/**
 * Main processing function.
 * @param filePath absolute path to the uploaded file.
 * @param preview if true, no DB writes are performed.
 */
export async function processFile(filePath: string, preview = false): Promise<ImportReport> {
  const rows = readFile(filePath);
  if (!rows || rows.length === 0) {
    throw new Error('File appears empty or unreadable');
  }

  // First row assumed to be headers (may be merged or missing)
  const rawHeaders: any[] = rows[0];
  const { headers, ignoredColumns } = normalizeHeaders(rawHeaders);

  if (headers.length !== 15) {
    // Not a fatal error – just a warning we will record later
  }

  const reports: RowResult[] = [];
  const uniquePhones = new Set<string>();
  const uniqueAcademicIds = new Set<string>();

  // Process each data row (skip header row)
  for (let i = 1; i < rows.length; i++) {
    const rawRow = rows[i];
    const original: RowOriginal = {};
    const processed: RowOriginal = {};
    const warnings: string[] = [];
    let failed = false;

    // Map cells to header names (using index)
    for (let col = 0; col < headers.length; col++) {
      const key = headers[col] || `Column_${col + 1}`;
      const value = rawRow[col];
      original[key] = value;
      processed[key] = value;
    }

    // ----- Auto‑fix strategies -----
    // Student name
    if (!processed['اسم الطالب'] && !processed['student_name']) {
      const genName = `طالب_مؤقت_${i}`;
      processed['اسم الطالب'] = genName;
      warnings.push('Missing student name – autogenerated temporary name');
    }

    // Phone
    const phoneKey = processed['جوال'] ?? processed['phone'];
    if (!phoneKey) {
      let newPhone = generatePhone();
      // ensure uniqueness within this import batch
      while (uniquePhones.has(newPhone)) newPhone = generatePhone();
      uniquePhones.add(newPhone);
      processed['جوال'] = newPhone;
      warnings.push('Missing phone – autogenerated unique placeholder');
    } else {
      uniquePhones.add(phoneKey);
    }

    // Academic ID (الرقم الجامعي)
    const acadKey = processed['الرقم الجامعي'] ?? processed['university_id'];
    if (!acadKey) {
      let newId = generateAcademicId();
      while (uniqueAcademicIds.has(newId)) newId = generateAcademicId();
      uniqueAcademicIds.add(newId);
      processed['الرقم الجامعي'] = newId;
      warnings.push('Missing academic ID – autogenerated unique ID');
    } else {
      uniqueAcademicIds.add(acadKey);
    }

    // Password
    if (!processed['password']) {
      processed['password'] = generatePassword();
      warnings.push('Missing password – autogenerated default password');
    }

    // Department – infer from subject if possible
    const deptKey = processed['تخصص'] ?? processed['department'];
    if (!deptKey) {
      const subject = processed['المادة'] || processed['subject_name'];
      let inferred = '';
      if (subject && typeof subject === 'string') {
        // naive inference – look for known keywords in subject name
        if (/هندسة/.test(subject)) inferred = 'هندسة البرمجيات';
        else if (/علوم/.test(subject)) inferred = 'علوم الحاسب';
        else if (/نظم/.test(subject)) inferred = 'نظم المعلومات';
      }
      processed['تخصص'] = inferred || 'عام';
      warnings.push(`Missing department – inferred as '${processed['تخصص']}'`);
    }

    // Subject – if empty, keep as null (allowed)
    if (!processed['المادة'] && !processed['subject_name']) {
      processed['المادة'] = null;
    }

    // Collect row result
    reports.push({ original, processed, warnings, failed });
  }

  // Prepare bulk upserts (only if not preview)
  if (!preview) {
    // Refresh schema first to avoid cache errors
    await refreshSchema(['students', 'departments', 'subjects']);
    // Upsert students – we assume the processed objects contain the needed fields
    const students = reports.map(r => ({
      university_id: r.processed['الرقم الجامعي'] ?? r.processed['university_id'],
      student_name: r.processed['اسم الطالب'] ?? r.processed['student_name'],
      phone: r.processed['جوال'] ?? r.processed['phone'],
      password: r.processed['password'],
      department: r.processed['تخصص'] ?? r.processed['department']
    }));

    // Use existing runWithRetry wrapper (imports supabase from lib)
    await runWithRetry(async () => {
      const { data, error } = await (await import('../lib/supabase')).supabase
        .from('students')
        .upsert(students, { onConflict: 'university_id' })
        .select();
      if (error) throw error;
      return data;
    });
    // Similar upserts for departments and subjects could be added here (omitted for brevity)
  }

  // Build final statistics
  const totalRows = reports.length;
  const successfulRows = reports.filter(r => !r.failed).length;
  const failedRows = totalRows - successfulRows;
  const warningsCount = reports.reduce((sum, r) => sum + r.warnings.length, 0);
  const autoFixedRows = reports.filter(r => r.warnings.length > 0).length;

  const report: ImportReport = {
    totalRows,
    successfulRows,
    failedRows,
    warningsCount,
    ignoredColumns,
    autoFixedRows,
    rowDetails: reports
  };

  return report;
}
